name: deploy gh-pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      MY_SECRET   : ${{secrets.cutSecrete}}
      USER_NAME   : githubaction
      USER_EMAIL  : githubaction@fake.com
      PUBLISH_DIR : ./dist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm deploy
      run: |
        npm run deploy